mybatis:
#  config-location: mybatis-config.xml
  mapper-locations: classpath:/mapper/EmployeeMapper.xml
  type-aliases-package: com.wondertek.mybatis.domain
#  configuration-properties: mybatis-config.xml
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
       # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/mybatis?allowMultiQueries=true
#
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

